---

- name: Install verdaccio
  npm:
    name: verdaccio
    global: true
    version: "{{ verdaccio_version }}"

- name: Add log-rotation patch
  patch:
    src: logrotate.patch
    basedir: /usr/lib/node_modules/verdaccio
    strip: 1
  ignore_errors: |
    {{ ansible_check_mode }}

- name: Create verdaccio group
  group:
    name: "{{ verdaccio_user }}"

- name: Create verdaccio user
  user:
    name: "{{ verdaccio_user }}"
    group: "{{ verdaccio_user }}"
    system: yes

- name: Create data directory
  file:
    path: "{{ verdaccio_storage }}"
    state: directory
    owner: "{{ verdaccio_user }}"
    group: "{{ verdaccio_user }}"

- name: Ensure, log-file exists and is aproperly owned
  copy:
    dest: "{{ verdaccio_log_file }}"
    owner: "{{ verdaccio_user }}"
    group: "{{ verdaccio_user }}"
    mode: 0644
    force: false
    content: ''
  when: verdaccio_log_file is defined

- name: Create config directory(ies)
  file:
    path: '/{{ item }}'
    state: directory
    mode: 0755
    group: "{{ verdaccio_user }}"
  with_items:
    - etc/init
    - etc/logrotate.d
    - etc/verdaccio
  ignore_errors: "{{ ansible_check_mode }}"

- name: Process configuration template(s)
  template:
    src: "{{ item }}.j2"
    dest: "/{{ item }}"
    mode: 0644
    group: "{{ verdaccio_user }}"
  with_items:
    - etc/init/verdaccio.conf
    - etc/systemd/system/verdaccio.service
    - etc/logrotate.d/verdaccio
    - etc/verdaccio/config.yaml
  notify: restart verdaccio

- name: Copy configuration file(s)
  copy:
    dest: '/{{ item }}'
    src: '{{ item }}'
    mode: 0640
    group: "{{ verdaccio_user }}"
  with_items:
    # TODO letsencrypt instead of static cert
    - etc/verdaccio/npm.rf29.net.pem
    - etc/verdaccio/users
  notify: restart verdaccio

- name: Start Verdaccio service on trusty
  service:
    name: verdaccio
    state: started
  when: ansible_distribution_release == 'trusty'

- name: Enable and start Verdaccio systemd service
  when: ansible_service_mgr == 'systemd'
  systemd:
    name: verdaccio.service
    daemon_reload: yes
    state: started
    enabled: true
